# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

lighthouse-geth-001:
  global:
    main:
      network: peerdas-devnet-7
      engineEndpoint: http://geth-lighthouse-001:8551
      rpcEndpoint: http://geth-lighthouse-001:8545
      beaconEndpoint: http://lighthouse-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        peerdas-devnet-7: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.peerdas-devnet-7.ethpandaops.io
    clientArgs:
      networks:
        peerdas-devnet-7:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://337be7e4cf5f37486495de1c1a5437d72ec3fee28da746285643097a8a4fd230ad2ffaef71d38ce4a1c39410d1a90de7e6f87c991e030953890f6801764957eb@157.245.70.213:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://337be7e4cf5f37486495de1c1a5437d72ec3fee28da746285643097a8a4fd230ad2ffaef71d38ce4a1c39410d1a90de7e6f87c991e030953890f6801764957eb@157.245.70.213:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Seq.ServerUrl=https://seq.nethermind.io
              - --Seq.ApiKey=yuOqjKOHhZCw2D2U7pmL
              - --Metrics.PushGatewayUrl=http://94.237.52.161:9000/metrics/nethermind-iudiy4raagaizaih1phuaShekighoJ2ixaecahvii7ohte3oozeeh0eTh7Aich1Shee9ceetuy3iGhexoh5naithoot8rebi7fee
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --networkid=7067938840
              - --syncmode=full
              - --bootnodes=enode://337be7e4cf5f37486495de1c1a5437d72ec3fee28da746285643097a8a4fd230ad2ffaef71d38ce4a1c39410d1a90de7e6f87c991e030953890f6801764957eb@157.245.70.213:30303?discport=30303
              - --rpc.allow-unprotected-txs
            erigon:
              - --chain=dev
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7067938840
              - --db.size.limit=500GB
              - --bootnodes=enode://337be7e4cf5f37486495de1c1a5437d72ec3fee28da746285643097a8a4fd230ad2ffaef71d38ce4a1c39410d1a90de7e6f87c991e030953890f6801764957eb@157.245.70.213:30303?discport=30303
            ethereumjs:
              - --gethGenesis=/data/network-config/genesis.json
              - --bootnodes=enode://337be7e4cf5f37486495de1c1a5437d72ec3fee28da746285643097a8a4fd230ad2ffaef71d38ce4a1c39410d1a90de7e6f87c991e030953890f6801764957eb@157.245.70.213:30303?discport=30303
              - --maxPeers=75
              - --isSingleNode=true
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QMNjMXusjOZ3z4-LVCpPR4AyhPbPFrhjc7yI47D0MuJZIPOXkS5jEauJYt42ZTcwD2-iozc0a7Kyfn1Vq5D6wbaGAZa04PiJgmlkgnY0gmlwhJ31RtWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-Oq4QO3tcA7uYreXLRwsLgDOTumg8T7GRKzB4sb0wpCcCBT3E-twXE2_PDdIzEqa-nxKBor7oHBe4AGOtuxCZkysH4cDh2F0dG5ldHOIAAAAAAADAACDY2djgYCGY2xpZW502IpMaWdodGhvdXNljDcuMS4wLWJldGEuMIRldGgykINHhMZwVSZHigIAAAAAAACCaWSCdjSCaXCEnfVG1YRxdWljgiMpiXNlY3AyNTZrMaEDIVZirGkL1LivoyIMVhX3sh_mxWs6fIuv17dKKkTGfdOIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QMNjMXusjOZ3z4-LVCpPR4AyhPbPFrhjc7yI47D0MuJZIPOXkS5jEauJYt42ZTcwD2-iozc0a7Kyfn1Vq5D6wbaGAZa04PiJgmlkgnY0gmlwhJ31RtWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-Oq4QO3tcA7uYreXLRwsLgDOTumg8T7GRKzB4sb0wpCcCBT3E-twXE2_PDdIzEqa-nxKBor7oHBe4AGOtuxCZkysH4cDh2F0dG5ldHOIAAAAAAADAACDY2djgYCGY2xpZW502IpMaWdodGhvdXNljDcuMS4wLWJldGEuMIRldGgykINHhMZwVSZHigIAAAAAAACCaWSCdjSCaXCEnfVG1YRxdWljgiMpiXNlY3AyNTZrMaEDIVZirGkL1LivoyIMVhX3sh_mxWs6fIuv17dKKkTGfdOIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --bootstrap-node=enr:-Iq4QMNjMXusjOZ3z4-LVCpPR4AyhPbPFrhjc7yI47D0MuJZIPOXkS5jEauJYt42ZTcwD2-iozc0a7Kyfn1Vq5D6wbaGAZa04PiJgmlkgnY0gmlwhJ31RtWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-Oq4QO3tcA7uYreXLRwsLgDOTumg8T7GRKzB4sb0wpCcCBT3E-twXE2_PDdIzEqa-nxKBor7oHBe4AGOtuxCZkysH4cDh2F0dG5ldHOIAAAAAAADAACDY2djgYCGY2xpZW502IpMaWdodGhvdXNljDcuMS4wLWJldGEuMIRldGgykINHhMZwVSZHigIAAAAAAACCaWSCdjSCaXCEnfVG1YRxdWljgiMpiXNlY3AyNTZrMaEDIVZirGkL1LivoyIMVhX3sh_mxWs6fIuv17dKKkTGfdOIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QMNjMXusjOZ3z4-LVCpPR4AyhPbPFrhjc7yI47D0MuJZIPOXkS5jEauJYt42ZTcwD2-iozc0a7Kyfn1Vq5D6wbaGAZa04PiJgmlkgnY0gmlwhJ31RtWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-Oq4QO3tcA7uYreXLRwsLgDOTumg8T7GRKzB4sb0wpCcCBT3E-twXE2_PDdIzEqa-nxKBor7oHBe4AGOtuxCZkysH4cDh2F0dG5ldHOIAAAAAAADAACDY2djgYCGY2xpZW502IpMaWdodGhvdXNljDcuMS4wLWJldGEuMIRldGgykINHhMZwVSZHigIAAAAAAACCaWSCdjSCaXCEnfVG1YRxdWljgiMpiXNlY3AyNTZrMaEDIVZirGkL1LivoyIMVhX3sh_mxWs6fIuv17dKKkTGfdOIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-Iq4QMNjMXusjOZ3z4-LVCpPR4AyhPbPFrhjc7yI47D0MuJZIPOXkS5jEauJYt42ZTcwD2-iozc0a7Kyfn1Vq5D6wbaGAZa04PiJgmlkgnY0gmlwhJ31RtWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-Oq4QO3tcA7uYreXLRwsLgDOTumg8T7GRKzB4sb0wpCcCBT3E-twXE2_PDdIzEqa-nxKBor7oHBe4AGOtuxCZkysH4cDh2F0dG5ldHOIAAAAAAADAACDY2djgYCGY2xpZW502IpMaWdodGhvdXNljDcuMS4wLWJldGEuMIRldGgykINHhMZwVSZHigIAAAAAAACCaWSCdjSCaXCEnfVG1YRxdWljgiMpiXNlY3AyNTZrMaEDIVZirGkL1LivoyIMVhX3sh_mxWs6fIuv17dKKkTGfdOIc3luY25ldHMAg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-lighthouse-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/geth
      tag: peerdas-devnet-7-f203dfc
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31961
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: peerdas-devnet-7
      testnet: peerdas-devnet-7
      ethereum_network: peerdas-devnet-7
      ethereum_role: execution
      consensus_client: lighthouse
      execution_client: geth
      ethereum_instance: geth-lighthouse-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.peerdas-devnet-7.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.peerdas-devnet-7.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.peerdas-devnet-7.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.peerdas-devnet-7.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethpandaops/geth:peerdas-devnet-7-f203dfc
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  lighthouse:
    checkpointSync:
      enabled: false
      addresses:
        peerdas-devnet-7: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.peerdas-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.peerdas-devnet-7.ethpandaops.io
    enabled: true
    fullnameOverride: lighthouse-geth-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/lighthouse
      tag: peerdas-devnet-7-4de1a73
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32442
    podLabels:
      network: peerdas-devnet-7
      testnet: peerdas-devnet-7
      ethereum_network: peerdas-devnet-7
      ethereum_role: consensus
      consensus_client: lighthouse
      execution_client: geth
      ethereum_instance: lighthouse-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.peerdas-devnet-7.ethpandaops.io/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.peerdas-devnet-7.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.peerdas-devnet-7.ethpandaops.io/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.peerdas-devnet-7.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.peerdas-devnet-7.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.peerdas-devnet-7.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
