default_ethereum_client_images:
### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:unstable-8cf686f
  lodestar: ethpandaops/lodestar:peerDAS-513bccc
  nimbus: ethpandaops/nimbus-eth2:pdsync-a479c7b
  prysm: ethpandaops/prysm-beacon-chain:peerDAS-2ab8c3b
  prysm_validator: ethpandaops/prysm-validator:peerDAS-ae626d5
  teku: ethpandaops/teku:nashatyrev-das-cefa2c5
  grandine: ethpandaops/grandine:hangleang-feature-das-9153c36
### Execution layer clients
  besu: hyperledger/besu:latest
  geth: ethereum/client-go:stable
  erigon: thorax/erigon:devel
  ethereumjs: ethpandaops/ethereumjs:master
  nethermind: nethermindeth/nethermind:master
  reth: ethpandaops/reth:main